project_name: cleanup

env:
  - GO111MODULE=on
  - CGO_ENABLED=1
  - LDFLAGS=-lpthread

builds:
  - id: linux-build
    env:
    - CGO_ENABLED=1
    - CC=aarch64-linux-gnu-gcc
    goos:
    - linux
    ignore:
    - goos: linux
      goarch: 386
  - id: darwin-build
    ldflags:
    - -s
    env:
    - CGO_ENABLED=1
    - CC=/home/runner/work/osxcross/target/bin/o64-clang
    - CXX=/home/runner/work/osxcross/target/bin/o64-clang++
    goos:
    - darwin
    ignore:
    - goos: darwin
      goarch: 386
  - id: windows-amd64
    binary: cleanup-windows-{{ .Arch }}
    env: 
    - CC=x86_64-w64-mingw32-gcc
    - CGO_ENABLED=1 
    main: ./main.go
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -buildmode=exe 
    no_unique_dist_dir: true