project_name: cleanup

env:
  - GO111MODULE=on
  - CGO_ENABLED=1
  - LDFLAGS=-lpthread

builds:
  - id: linux-amd64
    binary: cleanup-linux-{{ .Arch }}
    main: ./main.go
    goos:
      - linux
    goarch:
      - amd64 
    no_unique_dist_dir: true

  - id: darwin-amd64
    binary: cleanup-darwin-{{ .Arch }}
    env:
    - CGO_ENABLED=1
    - CC=/home/runner/work/osxcross/target/bin/o64-clang
    - CXX=/home/runner/work/osxcross/target/bin/o64-clang++
    ldflags:
      - -s
    main: ./main.go
    goos:
      - darwin
    goarch:
      - amd64 
    no_unique_dist_dir: true 
    
  - id: windows-amd64
    binary: cleanup-windows-{{ .Arch }}
    main: ./main.go
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -buildmode=exe 
    no_unique_dist_dir: true