name: Release Go project

on:
  push:
    tags:
      - "*" # triggers only if push new tag version, like `0.8.4` or else

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0    
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
          cache: true 
      - name: OSXCross for CGO Support
        run: |
          sudo apt-get install gcc-multilib -y
          sudo apt-get install gcc-mingw-w64 -y
          sudo apt-get -y install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu 
          mkdir ../../osxcross
          git clone https://github.com/plentico/osxcross-target.git ../../osxcross/target
      - uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}